class Entities:
    WebServer = "WebServer"
    Hostname = "Hostname"
    UserAgent = "UserAgent"
    Service = "Service"
    SSHServer = "SSHServer"
    SSHClient = "SSHClient"
    BuildNumber = "BuildNumber"
    Domain = "Domain"
    User = "User"


class Connections:
    ActiveService = "ActiveService"
    HTTP = "HTTPConnection"
    HTTPS = "HTTPSConnection"
    HTTPUserAgent = "HTTPUserAgent"
    ResolvedHostname = "ResolvedHostname"
    SSHClient = "SSHClient"
    SSHConnection = "SSHConnection"
    ComputerInfo = "ComputerInfo"
    LocalUser = "LocalUser"
    DomainUser = "DomainUser"
    DomainComputer = "DomainComputer"
    SMB = "SMBConnection"
